package com.example.dllo.mirror.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.mirror.db.HomeData;

import com.example.dllo.mirror.db.HomeDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeDataDaoConfig;

    private final HomeDataDao homeDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeDataDaoConfig = daoConfigMap.get(HomeDataDao.class).clone();
        homeDataDaoConfig.initIdentityScope(type);

        homeDataDao = new HomeDataDao(homeDataDaoConfig, this);

        registerDao(HomeData.class, homeDataDao);
    }
    
    public void clear() {
        homeDataDaoConfig.getIdentityScope().clear();
    }

    public HomeDataDao getHomeDataDao() {
        return homeDataDao;
    }

}
