package com.example.dllo.mirror.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HOME_DATA".
 */
public class HomeData {

    private Long id;
    private Short menu;
    private Short name;
    private Short resource;
    private Short price;
    private Short brand;

    public HomeData() {
    }

    public HomeData(Long id) {
        this.id = id;
    }

    public HomeData(Long id, Short menu, Short name, Short resource, Short price, Short brand) {
        this.id = id;
        this.menu = menu;
        this.name = name;
        this.resource = resource;
        this.price = price;
        this.brand = brand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Short getMenu() {
        return menu;
    }

    public void setMenu(Short menu) {
        this.menu = menu;
    }

    public Short getName() {
        return name;
    }

    public void setName(Short name) {
        this.name = name;
    }

    public Short getResource() {
        return resource;
    }

    public void setResource(Short resource) {
        this.resource = resource;
    }

    public Short getPrice() {
        return price;
    }

    public void setPrice(Short price) {
        this.price = price;
    }

    public Short getBrand() {
        return brand;
    }

    public void setBrand(Short brand) {
        this.brand = brand;
    }

}
